# -*- coding: utf-8 -*-
"""Trabajo final phyton Rodrigo Ferrúa y Adrian Hernandez.ipynb.json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jsF__TVA28ELEc3lwrFmfli3Z_fBjTzF
"""

#Integrantes: Rodrigo Ferrúa (20241000) y Adrián Hernandez (20242083)

#En primer lugar, se importa la biblioteca Pandas para que pueda leer la base de datos
import pandas as pd
#Luego se da la orden para que lea la base de datos, por lo cual se adjunta la ruta
df = pd.read_excel(str("Base de datos Actividades culturales Rodrigo Ferrúa y Adrián Hernandez.xlsx"))

#A continuación se saluda al usuario y se le comenta para qué sirve la página
print("¡Bienvenido, estimado usuario!, Estamos complacidos de poder ayudarlo en su búsqueda de una actividad recreativa y cultural para el día de hoy o para que planees en tus próximos días 😁")
print("¿En cuál de estos 5 tipos de actividad estarías interesado en participar hoy?")

#Se genera el primer filtro (pregunta 1) que son las opciones de qué tipo de actividad cultural ofrecemos en nuestra base de datos. Se imprimen para qué el usuario pueda elegir

print("1. TEATRAL")
print("2. EDUCATIVO")
print("3. CONCIERTO")
print("4. LITERATURA")
print("5. POESIA")

#A la par que generamos el bucle para que el usuario solamente pueda elegir alguna de nuestras opciones
opcion = 0
while opcion not in [1, 2, 3, 4, 5]:
    opcion = int(input("Escriba el número correspondiente al tipo de actividad que le interese: "))
    if opcion not in [1, 2, 3, 4, 5]:
        print("Opción NO válida 😞. Inténtelo nuevamente")

#En este punto se programa la cadena del condicional "if" y "elif" para que el programa pueda responder a las exigencias del usuario
if opcion == 1:
    TIPO_DE_ACTIVIDAD = "TEATRAL"
elif opcion == 2:
    TIPO_DE_ACTIVIDAD = "EDUCATIVO"
elif opcion == 3:
    TIPO_DE_ACTIVIDAD = "CONCIERTO"
elif opcion == 4:
    TIPO_DE_ACTIVIDAD = "LITERATURA"
elif opcion == 5:
    TIPO_DE_ACTIVIDAD = "POESIA"

#Creamos las variables con las que el programa pueda trabajar los "inputs" del usuario
#Generamos el segundo filtro para la búsqueda
print("¿Deseas obtener información de los eventos más recientes (del año 2025 🙃) o los próximos (2026) a los que puedas planear ir 😊?")
AÑO = 0
while AÑO not in [2025, 2026]:
    AÑO = int(input("Escriba el año 2025 o 2026: "))
    if AÑO not in [2025, 2026]:
        print("No contamos con información sobre ese año 🤭. Vuelve a intentarlo")

#Generamos el tercer filtro para la búsqueda: el horario
print("Bueno, ahora nos gustaría saber en qué momento del día te gustaría tu pequeña aventura cultural")
print("¿Deseas un evento que comience por la mañana ☀️ / tarde 🌇 / noche 🌑?")

#creamos la cadena para que pregunte por un horario disponible
while True:
    momento = input("Escriba (mañana/tarde/noche): ").strip().lower()
    if momento in ["mañana", "tarde", "noche"]:
        break
    else:
        print("Mmm... Creo que no contemplamos ese horario 😐. Inténtalo de nuevo")
#a continuación, hacemos el DataFrame para que el programa lea qué intervalos de tiempo en la base de datos, se pueden considerar "mañana", "tarde", y "noche", respectivamente
if momento == "mañana":
    df_filtrado = df[
        (df["HORA_INICIO"] >=500) &
        (df["HORA_INICIO"] <=1159)
    ]

elif momento == "tarde":
    df_filtrado = df[
        (df["HORA_INICIO"] >=1200) &
        (df["HORA_INICIO"] <=1859)
    ]

elif momento == "noche":
    df_filtrado = df[
        ((df["HORA_INICIO"] >=1700) & (df["HORA_INICIO"] <=2359)) |
        ((df["HORA_INICIO"] >=0) & (df["HORA_INICIO"] <= 459))
    ]

#Por último en este primer apartado, preguntamos por el último filtro para darle al usuario nuestra selección de eventos culturales: el aforo
print("¿Te molestaría estar en un lugar repleto de gente? O, por el contrario, ¿Quisieras compartir con la mayor cantidad de gente está actividad?")
print("Elige qué tanto aforo te gustaría para la actividad que estás a punto de escoger?")

#volvemos a crear la cadena de pregunta
while True:
    aforo = input("Escriba (pequeño/mediano/grande): ").strip().lower()
    if aforo in ["pequeño", "mediano", "grande"]:
        break
    else:
        print("Lo sentimos 😔. Debe escoger un aforo en dichos términos")

#Volvemos a hacer el DataFrame para esta cateogría
if aforo == "pequeño":
    df_filtrado = df_filtrado[
        (df["AFORO_MINIMO"] >=0) &
        (df["AFORO_MINIMO"] <=300)
    ]

elif aforo == "mediano":
    df_filtrado = df_filtrado[
        (df["AFORO_MINIMO"] >=301) &
        (df["AFORO_MINIMO"] <=1500)
    ]

elif aforo == "grande":
    df_filtrado = df_filtrado[
        (df["AFORO_MINIMO"] >=1500) &
        (df["AFORO_MINIMO"] <=10000)
    ]

#Finalmente se recogen todos los datos en un diccionario para que el programa pueda trabajarlos
Datos_recogidos = {
    "Característica": TIPO_DE_ACTIVIDAD,
    "Año": AÑO,
    "Momento": momento,
    "Aforo": aforo
}

#Y con los datos trabajados con DataFrame, creamos un diccionario


print("Datos_recogidos: " + str(Datos_recogidos))


#Luego pasamos con la programación del mapa

#Se importan las bibliotecas de folium y webbrowser para que el programa pueda ejecutar el mapa
import folium

import webbrowser

#Se le indica al programa que, en base a los datos filtrados, haga la selección de eventos que cumplen con las preferencias del usuario para posteriormente trabajarlos en el mapa

datos = df[
    (df["TIPO_DE_ACTIVIDAD"] == TIPO_DE_ACTIVIDAD) &
    (df["AÑO"] == AÑO)]

#Este es el código para que el programa pueda generar el mapa con los datos
if len(datos) > 0:

    mapa = folium.Map(
        location=[datos.iloc[0]["LATITUD"], datos.iloc[0]["LONGITUD"]],
        zoom_start=13
    )

    for i in range(len(datos)):
        folium.Marker(
            location=[datos.iloc[i]["LATITUD"], datos.iloc[i]["LONGITUD"]],
            popup=datos.iloc[i]["NOMBRE_ACTIVIDAD"]
        ).add_to(mapa)

    mapa

else:
    print("No se encontraron actividades.")

#Finalmente se guarda el mapa
#Y se imprime
mapa

"""#11
Reviso que el código logra importar correctamente la base de datos con pandas, recoge información del usuario mediante inputs y genera un mapa con folium usando las coordenadas de latitud y longitud del Excel. Valoro que se haya intentado integrar una base de datos real con una visualización en mapa, y que los comentarios expliquen varios pasos del procedimiento. Sin embargo, el principal problema es que los datos recogidos del usuario no se usan para filtrar la base de datos: se pregunta por característica, año, hora y aforo, pero luego el mapa muestra todas las actividades, no solo las que coinciden con esos criterios. También falta validar qué ocurre si el usuario escribe una opción incorrecta, porque la variable `CARACTERISTICA_ACTIVIDAD` podría quedar sin definirse. Además, se lee el mismo archivo dos veces, se importa `webbrowser` pero no se usa, y no se guarda el mapa en un archivo HTML. En general, considero que el trabajo tiene una buena base y muestra un avance importante en lectura de datos y visualización, pero todavía necesita conectar la selección del usuario con el filtrado real de actividades para cumplir mejor el objetivo del programa.

"""